# Module 8 Exercise - Data Storytelling

In this exercise, you will **create a data story product with a data set of your choosing**. You can choose any data set you can find on the Internet or a data set related to your current line of work. 



**You will create visualizations to give a message, make a point, or convince your audience by using all the techniques we have 
seen throughout the course.**

This exercise is about creating a quickly consumable product; Do **NOT** create a report or lengthy power point presentation. You can choose a **poster format** or **few slides** to tell your story (with a unique angle) from the conclusions you derive for the audience you have decided. 

---

### How do I choose the data set? 

 - Make sure to choose a data set that has many attributes (not 2 or 3) and has a big sample size so that each category or a subgroup also have enough data points in them. 
 - Make sure to choose a data set with some provenance: how was it collected? Who collected it? Was there any preprocessing? What do the columns really mean? It's usually a **poor practice to choose the first data set you see from Kaggle**; it will cause headache later in the process. 
 - Do some preliminary descriptive analytics to see if columns have enough variance and low to none missing data. Columns with no variance won't be useful. 
 - Choose an **interesting data set:** rich enough to let you do some analytics; no Pokemon data or Stock price data (very limited analysis options in both). 

---

### What do I show in the poster/presentation? 

 - Nothing obvious. If you can't find anything interesting to report in the data set, your visualizations will not be useful. 
 - Figure out who your audience will be and give them something useful that they did not know before. 
 - If there are no trends in your data, there is no point to show line plots; if there are no correlations or clusters in your data, there is no point in scatter plots, etc. 
 - It may take some analysis to discover interesting things; aggregate data, use binning, look at the subgroups, etc. to see if you can find some useful information. 
 - Do NOT write a report; it has to be a **pdf** file with visualizations as described below. 
 - Look at the **good and bad examples** in the lab notebook and consult the links. 
 
---

**Here is a list of your tasks:**

1. Find a data set and **upload** it to your **exercises** folder in module 8. 

2. Write your R code **in THIS exercise notebook** to create your visualizations, and save them under the `exercises` folder.

3. Create a **narrative visualization document** using **any** software you want (Word, PowerPoint, Photoshop, Adobe, Canva, etc.) by **pasting your plots and creating all necessary elements** (captions, text annotations, layout, etc.) 

4. Save your end product as a **PDF FILE** and upload it to your **exercises** folder (**MAKE SURE TO NAME IT L8_Exercise.pdf**)

You should start with a clear message or angle in your mind for your audience, and filter and format your data accordingly, and create the visualizations that will **support that message**. 

You need to have **at least one major visualization, and a number of supporting smaller graphs (2, 3, or more)** in a nice layout. Make sure to have a **clean layout** they can follow, and **enough text annotations and captions** to make your message/point clear. 


You can choose any type of visualization that you believe will be most **effective** for the type of data, characteristics of the data, visual tasks, and the message you have chosen. 

You will be graded by the quality of your visualizations and storytelling; **make sure to use every principle you have learned in this course.** 

---

Following is to show how to save a plot to a file:

In [42]:
# this is how you save a plot to a file
library(ggplot2)

# comment this out to see the plot in the notebook 
png(filename="myplot.png")

# # your plot here..
qplot(carat, price, data = diamonds)

# # comment this out to see the plot in the notebook
dev.off()

Warning message:
“`qplot()` was deprecated in ggplot2 3.4.0.”

agg_record_187456993
                   2

Make sure you have all axis labels set in R notebook before you save your plot. You can adjust width and height when saving your plots.  Here is a reference to png() function:
https://stat.ethz.ch/R-manual/R-devel/library/grDevices/html/png.html

**Activity:**

In [2]:
library(dplyr)
library(tidyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [3]:
# Read your data here; 

# Clean it up, reformat it, filter it, sort it, group it, etc.

# Create your visualizations and save them as png files, then prepare your final pdf document elsewhere

# <- ALL YOUR CODE BELOW THIS POINT ->
Gen <- read.csv("./generation.csv",as.is=TRUE, header=TRUE)
population<- read.csv("./population_1960_2018.csv", as.is=TRUE, header=TRUE)

head(Gen)
head(population)

  X    Paper Glass Metals Plastics Food  Yard.trimmings All.other Total
1 1960 29985 6721  10818   391     12200 20000          8002       88117
2 1961 30943 7050  11094   583     12500 20500          8382       91052
3 1962 32538 7400  11069   772     12600 20800          8348       93527
4 1963 33631 7713  10861   979     12700 21200          8464       95548
5 1964 35767 8247  11861  1227     12700 21400          9243      100445
6 1965 38145 8725  12158  1484     12700 21600          9559      104371

  year POPTOTUSA647NWDB
1 1960 180671000
2 1961 183691000
3 1962 186538000
4 1963 189242000
5 1964 191889000
6 1965 194303000

In [4]:
#rename columns to be easier to reference
colnames(Gen)[colnames(Gen)=='X']<- "year"
colnames(Gen)[colnames(Gen)=='Yard.trimmings']<- "Yard"
colnames(Gen)[colnames(Gen)=='All.other']<- "Other"

colnames(population)[colnames(population)=='POPTOTUSA647NWDB']<-"population"

colnames(Gen)

colnames(population)

[1] "year"     "Paper"    "Glass"    "Metals"   "Plastics" "Food"     "Yard"
[8] "Other"    "Total"

[1] "year"       "population"

In [5]:
#merge populations to generation and recycling & composting tables
Gen <- merge(x=Gen, y=population, by="year", all.x=TRUE)
head(Gen)

  year Paper Glass Metals Plastics Food  Yard  Other Total  population
1 1960 29985 6721  10818   391     12200 20000 8002   88117 180671000
2 1961 30943 7050  11094   583     12500 20500 8382   91052 183691000
3 1962 32538 7400  11069   772     12600 20800 8348   93527 186538000
4 1963 33631 7713  10861   979     12700 21200 8464   95548 189242000
5 1964 35767 8247  11861  1227     12700 21400 9243  100445 191889000
6 1965 38145 8725  12158  1484     12700 21600 9559  104371 194303000

In [6]:
#convert thousand tons to tons and divide by population to get tons per person generated
Gen$WastePP <- (1000*Gen$Total)/Gen$population
head(Gen)

  year Paper Glass Metals Plastics Food  Yard  Other Total  population
1 1960 29985 6721  10818   391     12200 20000 8002   88117 180671000
2 1961 30943 7050  11094   583     12500 20500 8382   91052 183691000
3 1962 32538 7400  11069   772     12600 20800 8348   93527 186538000
4 1963 33631 7713  10861   979     12700 21200 8464   95548 189242000
5 1964 35767 8247  11861  1227     12700 21400 9243  100445 191889000
6 1965 38145 8725  12158  1484     12700 21600 9559  104371 194303000
  WastePP
1 0.4877208
2 0.4956802
3 0.5013831
4 0.5048985
5 0.5234537
6 0.5371559

In [7]:
#run summary to learn more about variables after cleaning up the data frame
summary(Gen)

      year          Paper           Glass           Metals         Plastics
 Min.   :1960   Min.   :29985   Min.   : 6721   Min.   :10818   Min.   :  391
 1st Qu.:1974   1st Qu.:50427   1st Qu.:11674   1st Qu.:14216   1st Qu.: 4348
 Median :1989   Median :67480   Median :12612   Median :15661   Median :15871
 Mean   :1989   Mean   :63255   Mean   :12244   Mean   :16848   Mean   :16171
 3rd Qu.:2004   3rd Qu.:77425   3rd Qu.:13258   3rd Qu.:19950   3rd Qu.:28625
 Max.   :2018   Max.   :88260   Max.   :15355   Max.   :25600   Max.   :35680
      Food            Yard           Other           Total
 Min.   :12200   Min.   :20000   Min.   : 8002   Min.   : 88117
 1st Qu.:13200   1st Qu.:25100   1st Qu.:13694   1st Qu.:134878
 Median :13400   Median :30000   Median :27911   Median :192250
 Mean   :22652   Mean   :28976   Mean   :27671   Mean   :187817
 3rd Qu.:32245   3rd Qu.:33050   3rd Qu.:39245   3rd Qu.:245175
 Max.   :63130   Max.   :35400   Max.   :53090   Max.   :292360
   population           WastePP
 Min.   :180671000   Min.   :0.4877
 1st Qu.:214913500   1st Qu.:0.6282
 Median :246819000   Median :0.7789
 Mean   :252657293   Mean   :0.7244
 3rd Qu.:291456616   3rd Qu.:0.8266
 Max.   :328529577   Max.   :0.8899

In [14]:
#use pivot_longer to change from each type as a column to each type as an entry per year
#this will make it easier to create a stacked bar chart of total waste split into type by year, include total waste for later step
GenLong <- Gen %>% select(-population, -WastePP) %>%pivot_longer(cols=-c(year, Total), names_to="WasteType", values_to="Amount")
head(GenLong, 15)

   year Total WasteType Amount
1  1960 88117 Paper     29985
2  1960 88117 Glass      6721
3  1960 88117 Metals    10818
4  1960 88117 Plastics    391
5  1960 88117 Food      12200
6  1960 88117 Yard      20000
7  1960 88117 Other      8002
8  1961 91052 Paper     30943
9  1961 91052 Glass      7050
10 1961 91052 Metals    11094
11 1961 91052 Plastics    583
12 1961 91052 Food      12500
13 1961 91052 Yard      20500
14 1961 91052 Other      8382
15 1962 93527 Paper     32538

In [15]:
#calculate the percentage each waste type is of the total per year
GenLong$PercTotal <- (GenLong$Amount/GenLong$Total)*100
head(GenLong)

  year Total WasteType Amount PercTotal
1 1960 88117 Paper     29985  34.0286210
2 1960 88117 Glass      6721   7.6273591
3 1960 88117 Metals    10818  12.2768592
4 1960 88117 Plastics    391   0.4437282
5 1960 88117 Food      12200  13.8452285
6 1960 88117 Yard      20000  22.6970959

In [13]:
#access the colors in the brewer palette Set3
#I like these colors but want to ensure each waste type is the same color in all graphs
RColorBrewer::brewer.pal(8, "Set3")

[1] "#8DD3C7" "#FFFFB3" "#BEBADA" "#FB8072" "#80B1D3" "#FDB462" "#B3DE69"
[8] "#FCCDE5"

In [45]:
#plot a stacked bar chart of all waste generated, assign  colors to each type, change axis labels, add labels, and change legend position
png(filename="stackedbar.png")
ggplot(GenLong, aes(x=year, y=Amount, fill=WasteType, color=WasteType))+geom_bar(stat="identity", position="stack")+
scale_fill_manual(values=c("Food"="#8DD3C7", "Glass"="#FCCDE5", "Metals"="#BEBADA", "Other"="#FB8072", "Paper"="#80B1D3", "Plastics"="#FDB462", "Yard"="#B3DE69")) + 
scale_color_manual(values=c("Food"="#8DD3C7", "Glass"="#FCCDE5", "Metals"="#BEBADA", "Other"="#FB8072", "Paper"="#80B1D3", "Plastics"="#FDB462", "Yard"="#B3DE69")) +
labs(title="Waste per Year Broken Down by Type", fill="Type of Waste", x="Year", y="Waste Generated in 1,000 tons") + 
theme_minimal() + guides(color="none") + scale_x_continuous(breaks = c(1960, 1970, 1980, 1990, 2000, 2010, 2020)) +
scale_y_continuous(breaks=c(0, 50000, 100000, 150000, 200000, 250000, 300000))+ 
theme(legend.position = "bottom", legend.justification=c("left", "bottom"))+ theme(text=element_text(size=15))
dev.off()

agg_record_1542650906
                    2

In [17]:
#group by year and use slice_max to find the max waste type per year
#assign less ambiguous column names so that it can be merged with the minimum data frame created next without any confusion
GenMax <- GenLong %>% group_by(year) %>% slice_max(Amount, n=1, with_ties=FALSE)
colnames(GenMax)[colnames(GenMax)=='WasteType']<- 'MaxWT'
colnames(GenMax)[colnames(GenMax)=='Amount']<- 'MaxAmount'
head(GenMax)

  year Total  MaxWT MaxAmount PercTotal
1 1960  88117 Paper 29985     34.02862
2 1961  91052 Paper 30943     33.98388
3 1962  93527 Paper 32538     34.78995
4 1963  95548 Paper 33631     35.19802
5 1964 100445 Paper 35767     35.60854
6 1965 104371 Paper 38145     36.54751

In [18]:
#group by year and use slice_min to find the minimum waste type per year
#assign less ambiguous column names like above to allow for easier merging in the next step
GenMin <- GenLong %>% group_by(year) %>% slice_min(Amount, n=1, with_ties=FALSE)
colnames(GenMin)[colnames(GenMin)=='WasteType']<- 'MinWT'
colnames(GenMin)[colnames(GenMin)=='Amount']<- 'MinAmount'
head(GenMin)

  year Total  MinWT    MinAmount PercTotal
1 1960  88117 Plastics  391      0.4437282
2 1961  91052 Plastics  583      0.6402935
3 1962  93527 Plastics  772      0.8254301
4 1963  95548 Plastics  979      1.0246159
5 1964 100445 Plastics 1227      1.2215640
6 1965 104371 Plastics 1484      1.4218509

In [46]:
png(filename="percentchange.png")
ggplot(GenLong)+geom_line(aes(x=year, y=PercTotal, color=WasteType)) +theme_minimal() + 
scale_color_manual(values=c("Food"="#8DD3C7", "Glass"="#FCCDE5", "Metals"="#BEBADA", "Other"="#FB8072", "Paper"="#80B1D3", "Plastics"="#FDB462", "Yard"="#B3DE69")) +
labs(title= "Change in Waste Types by Year",x="Year", y="Percent of Total Waste", color="Type of Waste") + theme(text=element_text(size=15))
dev.off()

agg_record_1701776485
                    2

In [20]:
#merge the GenMax and GenMin data frames to be able plot them on the same plot easily
GMinMax<-merge(x=GenMax, y=GenMin, by="year", all.x=TRUE, all.y=TRUE)
head(GMinMax)

  year Total.x MaxWT MaxAmount PercTotal.x Total.y MinWT    MinAmount
1 1960  88117  Paper 29985     34.02862     88117  Plastics  391
2 1961  91052  Paper 30943     33.98388     91052  Plastics  583
3 1962  93527  Paper 32538     34.78995     93527  Plastics  772
4 1963  95548  Paper 33631     35.19802     95548  Plastics  979
5 1964 100445  Paper 35767     35.60854    100445  Plastics 1227
6 1965 104371  Paper 38145     36.54751    104371  Plastics 1484
  PercTotal.y
1 0.4437282
2 0.6402935
3 0.8254301
4 1.0246159
5 1.2215640
6 1.4218509

In [47]:
#plot the minimum and maximum amounts, color corresponds to type and shape corresponds to minimum or maximum amount
png(filename="minmax.png")
ggplot(GMinMax)  + geom_point(aes(x=year, y=MaxAmount, color=MaxWT, shape="Maximum")) +
geom_point(aes(x=year, y=MinAmount, color=MinWT, shape="Minimum"))+theme_minimal()+
labs(title="Maximum & Minimum Waste Type Per Year", 
x="Year", y="Waste in 1,000 tons", color="Type of Waste", shape="") + 
scale_color_manual(values=c("Paper"="#80B1D3","Glass"="#FCCDE5","Plastics"="#FDB462"))+ 
theme(legend.position = "bottom", , legend.box="vertical")+ theme(text=element_text(size=15))
dev.off()

agg_record_12912475
                  2

In [22]:
#the next two are earlier plots from when I was going to have separate max and min plots
gmax<-ggplot(GenMax, aes(x=year, y=Amount, color=WasteType))  + geom_point() +theme_minimal()+
labs(title="Maximum Waste Type Per Year", subtitle="All waste generated", 
x="Year", y="Waste in 1,000 tons", color="Type of Waste") + scale_color_manual(values=c("Paper"="#80B1D3"))

In [23]:
gmin<-ggplot(GenMin, aes(x=year, y=Amount, color=WasteType))  + geom_point() + 
labs(title="Minimum Waste Type Per Year", subtitle="All Waste Generated", x="Year", y="Waste in 1,000 tons", color="Type of Waste") + 
scale_color_manual(values=c("Glass"="#FCCDE5","Plastics"="#FDB462"))+
theme_minimal()

In [48]:
png(filename="wastepp.png")
ggplot(Gen, aes(x=year, y=WastePP))+geom_line()+theme_minimal() + 
scale_x_continuous(breaks = c(1960, 1970, 1980, 1990, 2000, 2010, 2020))+
labs(title="Waste Per Person by Year", x="Year", y="Waste (in tons) Per Person")+ theme(text=element_text(size=15))
dev.off()

agg_record_1302563060
                    2

---

# Common Pitfalls / Inefficiencies

**BEFORE you submit your end product, pay attention to the following and check your visualizations and story accordingly.**

**Think of this as a rubric; you will lose points if you don't follow all the principles we have seen in this course.**

---

### - Remember the design analysis questions:

**what, how, who, why?** 

- What are you showing/telling? 
- How are you going to show it (efficiency? visual channels, colors, tasks like comparison, trends, query, etc.) 
- Who is your audience? Why should they care about what you have to tell? What are the **actionable** information they can take from your story? 
- Why are you telling the story? What is your angle, message, point? (make it clear in text AND visuals)

---

### - Pay attention to the color schemes/palettes:

 - Do NOT use sequential palettes for data attributes that have **no** ordering.
 - Do NOT use qualitative color schemes for attributes where order **matters**.

---

###  - Color coordinate among plots so that the same data attributes have the same color in all plots:

You can do that by creating a manual palette and use it everywhere to make sure same color is always assigned to the same attribute value (especially important for categories). Do not change color of the same category among plots!

---

###  - Perceptual grouping is important! group and/or order values:

People tend to make sense of things and compare better when they are ordered or grouped:  

- In a bar chart, **order the axes** by time, value, etc. to make comparisons more intuitive. 

- Pie chart: order wedges. 

- In a bubble map, if you want to show trends, use grouping variable to **connect** bubbles, etc.

---

### - No lengthy text in x axis:

- **Flip** the axes of a bar chart so that character values (text) are **readable on the y axis** left to right, 

**or** 

- at least, put them slanted in x axis for better readibility.

---

### - Plot only those data columns and/or subsets that tell a clear story:

 - **No crowded** scatter plots with useless linear regression lines that don't tell anything.  
 - You do **NOT** have to plot **ALL** your data (most of the time, you should not). 
 - Look at alternative plots to tell your story effectively. 
 - Your plots should be perceived easily and intuitively.

---

### - If you have too many classes (discrete variables/categories), try to GROUP them:

- Instead of giving a color to each of the dozen or so categories, you can put them in meaningful groups and color code to reduce clutter. 

- For sequential variables, you can do the same thing by **binning** numbers into bins (like in a histogram). 

- **Stepped color palettes** may be more useful than smooth sequential palettes (especially for comparison in choropleth maps) for a large range of values in an attribute. 

- You can **group/cluster data into meaningful chunks** and display those as bubble charts, networks, geographical regions, etc. 

- Do **NOT** dump all the data in the plot unless there is a CLEAR pattern/clustering to it that can be **perceived immediately**.

---

### - ANNOTATE! ANNOTATE! ANNOTATE!

- **Tell** your audience what they are supposed to see. 

- Use **meaningful** titles with a message/statement, no dry titles. 

- Use nice and concise axis labels (make sure they are large enough).

- Use text annotations (look at the **examples in the lab notebook**).

---

### - THEMING

- **Good looking** charts are more **convincing**! Your audience will have more confidence in your work. 

- **Almost NEVER use the default color palette, default theme, or default fonts.**

- Use a subtle color scheme, nice fonts, interesting glyphs, etc. to make your charts look more **sophisticated**.

---

### - Use space wisely!

- **Balance the plots** to use space effectively.

- Pay attention to **data-ink ratio**.

- **HAVE A FLOW left to right, top to bottom**. 

- If you must have a line plot or bar plot with a lot of empty space, try to put text annotations with relevant information in them.